Drop SnowPack because undefined is not a function 🤷‍♂️
Run npx snowpack@2 build
[snowpack] ! building source…
[snowpack] ✔ build complete [0.04s]
[snowpack] ! /home/runner/work/github-url-detection/github-url-detection/artifact/cjs/index.js

TypeError: undefined is not a function
    at parseJsForInstallTargets (/home/runner/.npm/_npx/2418/lib/node_modules/snowpack/lib/scan-imports.js:114:19)